apiVersion: v1
kind: ConfigMap
metadata:
  name: my-postgres-postgresql
data:
  DB_NAME: "mydatabase"
  DB_USERNAME: "myuser"
  DB_HOST: "my-postgres-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
